module.exports = {
  mediaItems: [
    {
      id: '1',
      title: 'Attack on Titan',
      type: 'anime',
      description: 'Una serie épica sobre la humanidad luchando contra gigantes.',
      image_url: 'https://images.pexels.com/photos/1170986/pexels-photo-1170986.jpeg',
      release_date: '2013-04-07',
      rating: 4.8,
      rating_count: 15420,
      genre: ['Acción', 'Drama', 'Fantasía'],
      status: 'completed',
      episodes: 87,
      cast: [
        { name: 'Yuki Kaji', character: 'Eren Yeager' },
        { name: 'Marina Inoue', character: 'Armin Arlert' },
        { name: 'Yui Ishikawa', character: 'Mikasa Ackerman' },
      ],
    },
    {
      id: '2',
      title: 'The Matrix',
      type: 'movie',
      description: 'Un programador descubre la verdad sobre la realidad.',
      image_url: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg',
      release_date: '1999-03-31',
      rating: 4.6,
      rating_count: 8930,
      genre: ['Ciencia Ficción', 'Acción'],
      status: 'completed',
      cast: [
        { name: 'Keanu Reeves', character: 'Neo' },
        { name: 'Laurence Fishburne', character: 'Morpheus' },
        { name: 'Carrie-Anne Moss', character: 'Trinity' },
      ],
    },
    {
      id: '3',
      title: 'Breaking Bad',
      type: 'series',
      description: 'Un profesor de química se convierte en fabricante de metanfetaminas.',
      image_url: 'https://images.pexels.com/photos/3137068/pexels-photo-3137068.jpeg',
      release_date: '2008-01-20',
      rating: 4.9,
      rating_count: 12750,
      genre: ['Drama', 'Thriller'],
      status: 'completed',
      episodes: 62,
      cast: [
        { name: 'Bryan Cranston', character: 'Walter White' },
        { name: 'Aaron Paul', character: 'Jesse Pinkman' },
        { name: 'Anna Gunn', character: 'Skyler White' },
      ],
    },
    {
      id: '4',
      title: 'One Piece',
      type: 'manga',
      description: 'Las aventuras de Monkey D. Luffy en busca del tesoro One Piece.',
      image_url: 'https://images.pexels.com/photos/2387793/pexels-photo-2387793.jpeg',
      release_date: '1997-07-22',
      rating: 4.7,
      rating_count: 18600,
      genre: ['Aventura', 'Comedia', 'Shonen'],
      status: 'ongoing',
      chapters: 1100,
      cast: [
        { name: 'Mayumi Tanaka', character: 'Monkey D. Luffy' },
        { name: 'Kazuya Nakai', character: 'Roronoa Zoro' },
        { name: 'Akemi Okamura', character: 'Nami' },
      ],
    },
    {
      id: '5',
      title: 'Interstellar',
      type: 'movie',
      description: 'Una misión espacial para salvar a la humanidad.',
      image_url: 'https://images.pexels.com/photos/73873/star-clusters-rosette-nebula-star-galaxies-73873.jpeg',
      release_date: '2014-11-07',
      rating: 4.5,
      rating_count: 9840,
      genre: ['Ciencia Ficción', 'Drama'],
      status: 'completed',
      cast: [
        { name: 'Matthew McConaughey', character: 'Cooper' },
        { name: 'Anne Hathaway', character: 'Amelia Brand' },
        { name: 'Jessica Chastain', character: 'Murph' },
      ],
    },
    {
      id: '6',
      title: 'Demon Slayer',
      type: 'anime',
      description: 'Tanjiro busca una cura para su hermana convertida en demonio.',
      image_url: 'https://images.pexels.com/photos/3137068/pexels-photo-3137068.jpeg',
      release_date: '2019-04-06',
      rating: 4.4,
      rating_count: 11200,
      genre: ['Acción', 'Sobrenatural'],
      status: 'ongoing',
      episodes: 44,
      cast: [
        { name: 'Natsuki Hanae', character: 'Tanjiro Kamado' },
        { name: 'Akari Kitō', character: 'Nezuko Kamado' },
        { name: 'Hiro Shimono', character: 'Zenitsu Agatsuma' },
      ],
    },
  ],
  forumPosts: [
    {
      id: 'post-1',
      user_id: '1',
      title: '¿Cuál es el mejor anime de 2024?',
      content: 'Quiero saber qué opinan sobre los animes que han salido este año. Para mí, Demon Slayer sigue siendo increíble.',
      category: 'anime',
      tags: ['temporada-2024', 'recomendaciones'],
      liked_by: ['2', '3'],
      created_at: '2024-01-15T10:30:00Z',
      updated_at: '2024-01-15T10:30:00Z',
      user: {
        id: '1',
        email: 'user1@example.com',
        username: 'AnimeFan2024',
        created_at: '2023-01-01T00:00:00Z',
      },
      comments: [
        {
          id: 'comment-1',
          post_id: 'post-1',
          user_id: '2',
          content: 'Jujutsu Kaisen está teniendo una animación brutal este año.',
          created_at: '2024-01-15T12:00:00Z',
          likes_count: 4,
          liked_by: ['1', '3'],
          replies: [
            {
              id: 'comment-1-1',
              post_id: 'post-1',
              user_id: '3',
              content: 'Totalmente de acuerdo, Frieren sorprendió.',
              created_at: '2024-01-15T13:45:00Z',
              likes_count: 2,
              liked_by: ['2'],
              replies: [],
            },
          ],
        },
      ],
    },
    {
      id: 'post-2',
      user_id: '2',
      title: 'Recomendaciones de películas de ciencia ficción',
      content: 'Busco películas de sci-fi que realmente me vuelen la cabeza.',
      category: 'movies',
      tags: ['ciencia-ficcion', 'peliculas'],
      liked_by: ['1'],
      created_at: '2024-01-14T15:20:00Z',
      updated_at: '2024-01-14T15:20:00Z',
      user: {
        id: '2',
        email: 'user2@example.com',
        username: 'SciFiLover',
        created_at: '2023-02-01T00:00:00Z',
      },
      comments: [
        {
          id: 'comment-2',
          post_id: 'post-2',
          user_id: '1',
          content: '¿Ya viste Arrival? Tiene un enfoque súper interesante.',
          created_at: '2024-01-14T18:10:00Z',
          likes_count: 3,
          liked_by: ['2'],
          replies: [],
        },
      ],
    },
    {
      id: 'post-3',
      user_id: '3',
      title: 'One Piece vs Naruto - Debate eterno',
      content: 'Sé que es un tema controversial, pero me gustaría saber sus argumentos.',
      category: 'manga',
      tags: ['shonen', 'debate'],
      liked_by: ['1', '2', '4'],
      created_at: '2024-01-13T09:45:00Z',
      updated_at: '2024-01-13T09:45:00Z',
      user: {
        id: '3',
        email: 'user3@example.com',
        username: 'MangaMaster',
        created_at: '2023-03-01T00:00:00Z',
      },
      comments: [],
    },
  ],
};
